name: Onboarding Request
description: Request that a software tool be onboarded to the NOAA Fisheries Integrated Toolbox (FIT).
title: "Onboarding Request: [tool name] "
labels: ["Onboarding Request"]
assignees:
  - k-doering-NOAA
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this onboarding request! Please take a look at the [onboarding slidedeck](https://noaa-fisheries-integrated-toolbox.github.io/FIT-Onboarding-Presentation/) for details about the onboarding process.
  - type: dropdown
    id: activedev
    attributes:
      label: Code status
      description: Is the code or tool in active development? (If inactive, please consider whether there is a replacement tool that should instead be onboarded to the toolbox).
      options:
        - Active
        - Inactive
    validations:
      required: true
  - type: input
    id: toolname
    attributes:
      label: Please provide the tool name
      placeholder: Stock Synthesis
    validations:
      required: true
  - type: input
    id: modelabbrev
    attributes:
      label: Please provide the tool abbreviation
      placeholder: SS3
    validations:
      required: true
  - type: textarea
    id: authorname
    attributes:
      label: Provide the name(s) of the Authors
      description: Please include in the format provided
      placeholder: Rick Methot, Ian Taylor, Kelli Johnson
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact
      description: Email address of main contact for this tool
      placeholder: fisheries.toolbox@noaa.gov
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Please provide a paragraph of background text on the tool.
      description: This will be the main text on the model landing page.
      placeholder: The Age Structured Assessment Program (ASAP) is an age-structured model that uses forward computations assuming separability of fishing mortality into year and age components to estimate population sizes given observed catches, catch-at-age, and indices of abundance. Discards can be treated explicitly. The separability assumption is relaxed by allowing for fleet-specific computations and by allowing the selectivity at age to change smoothly over time or in blocks of years. The software can also allow the catchability associated with each abundance index to vary smoothly with time. The problem’s dimensions (number of ages, years, fleets and abundance indices) are defined at input and limited by hardware only. The input is arranged assuming data is available for most years, but missing years are allowed. The model currently does not allow use of length data nor indices of survival rates. Diagnostics include index fits, residuals in catch and catch-at-age, and effective sample size calculations. Weights are input for different components of the objective function and allow for relatively simple age-structured production model type models up to fully parameterized models. The calculation engine was built using AD Model Builder by Drs. Christopher M. Legault (currently at the NMFS Northeast Fisheries Science Center) and Victor R. Restrepo (currently at the NMFS Southeast Fisheries Science Center). ASAP has been used as an assessment tool for red grouper (SEFSC), yellowtail flounder (NEFSC), Pacific sardine (SWFSC), Pacific mackerel (SWFSC), Greenland halibut (ICES), Norther Gulf of St. Lawrence cod (DFO), Gulf of Maine cod (NEFSC), Florida lobster (FFWCC), and fluke (NEFSC).
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References
      description: References related to the tool, include name and DOI
      placeholder: "Stock synthesis: A biological and statistical framework for fish stock assessment and fishery management, https://doi.org/10.1016/j.fishres.2012.10.012"
    validations:
      required: false
  - type: textarea
    id: associatedtools
    attributes:
      label: Provide name and link of any associated tools
      description:
      placeholder: ASAP https://nmfs-fish-tools.github.io/ASAP/
    validations:
      required: false

  # Links to the Tool
  - type: input
    id: onlineapplink
    attributes:
      label: Link to online application
      placeholder: https://connect.fisheries.noaa.gov/DLMapper/
    validations:
      required: false
  - type: input
    id: exelink
    attributes:
      label: Link to download executable(s)
      placeholder: https://github.com/nmfs-fish-tools/SSMSE/releases
    validations:
      required: false
  - type: input
    id: websitelink
    attributes:
      label: Tool website
      description: Link to website
      placeholder: https://vlab.noaa.gov/web/stock-synthesis
    validations:
      required: false            
  - type: input
    id: documentationlink
    attributes:
      label: Link to documentation
      placeholder: https://nmfs-fish-tools.github.io/SSMSE/manual/
    validations:
      required: false
  - type: input
    id: sourcecodelink
    attributes:
      label: Link to source code
      placeholder: https://github.com/nmfs-fish-tools/SSMSE
    validations:
      required: false
  # - type: input
  #   id: citelink
  #   attributes:
  #     label: Link a reference article for the tool for users to cite (preferably a DOI)
  #     placeholder: https://doi.org/10.1016/j.fishres.2012.10.012
  #   validations:
  #     required: false
  - type: input
    id: pdflink
    attributes:
      label: PDF to download
      description: If you would like to add a link to a pdf to download (e.g., documentation or a publication), please add a link below.
    validations:
      required: false
  - type: textarea
    id: badges
    attributes:
      label: Link to badges
      description:  Add up to 5 badges that you would like displayed. Separate them with commas.
      placeholder: https://www.repostatus.org/badges/latest/active.svg, https://img.shields.io/badge/platform-linux%20%7Cwin-lightgrey
    validations:
      required: false
  - type: checkboxes
    id: drawer
    attributes:
      label: Which drawer(s) of the toolbox does this tool belong in?
      description: Check any that apply.
      options:
        - label: Ecosystems
        - label: Fish and Fisheries
        - label: Human Dimensions
        - label: Protected Species
        - label: General Modeling and Productivity Tools
  - type: checkboxes
    id: keywords
    attributes:
      label: Keywords
      description: Check up to 5 keywords that describe the tool. Have other keyword suggests? Include in questions and comments.
      options:
        - label: Economics Model
        - label: Visualization
        - label: Stock Assessment Model
        - label: Ecosystem Model
        - label: Management Strategy Evaluation
        - label: Shiny app
  - type: dropdown
    id: releases
    attributes:
      label: Github Releases
      description: Does the codebase use releases on GitHub? (If not, we HIGHLY recommend considering using releases to keep the version number on the toolbox up to date)
      options: 
        - Yes
        - No
        - I plan to use them in the future
    validations:
      required: true
  - type: input
    id: versionnumber
    attributes:
      label: If not using GitHub releases and the version number is not likely to change, please add the latest version number. Please don't provide a version number if it will change frequently, as we don't have a good way to make sure it stays up to date if not using GitHub releases.
      placeholder: 0.9.0
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Questions and Comments
      description: Please add any additional questions or comments
      placeholder:
    validations:
      required: false
  # - type: checkboxes
  #   id: langs
  #   attributes:
  #     label: which language(s) is the tool written in? (note: could pull this from github meta data)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://noaa-fims.github.io/collaborative_workflow/code-of-conduct.html#code-of-conduct)
      options:
        - label: I agree to follow the FIT's [Code of Conduct](https://noaa-fims.github.io/collaborative_workflow/code-of-conduct.html#code-of-conduct)
          required: true
