name: Use the gh R pkg to get info from a PR
on: workflow_dispatch
jobs:
  test-get-info-pr-gh-r-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: install the gh pkg
        run: |
          install.packages("gh")
        shell: Rscript {0}
      - name: Get info
        run: |
          info <- gh::gh("GET /repos/{owner}/{repo}/pulls/{pull_number}", 
            owner = "k-doering-noaa", 
            repo = "test_github_site",
            pull_number = "22")
          print(info)
        shell: Rscript {0}
        
