name: Use the gh R pkg to get info from a PR and open issues in new repos
on: workflow_dispatch
jobs:
  get-info-pr-gh-open-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: install the gh pkg
        run: |
          install.packages("gh")
        shell: Rscript {0}
      - name: Get info
        run: |
          info <- gh::gh("GET /repos/{owner}/{repo}/pulls/{pull_number}", 
            owner = "k-doering-noaa", 
            repo = "test_github_site",
            pull_number = "24")
          pr_body  <- strsplit(info$body, "\n" )[[1]]
          pr_body <- gsub("\r", "",  pr_body, fixed = TRUE)
          # Get info on which repos need open issues, if a change log entry is needed.
          # allow some flexibility for getting the spacing wrong, which is easy to do.
          # look for checklist items like - []
          needs_changes <- grep("-\\s*\\[\\s*\\]", pr_body, ignore.case = TRUE, value = TRUE)
          # just do an if statement for each to determine which changes 
          r4ss <- change_log <- SSI <- manual <- FALSE
          if (length(grep("r4ss", needs_changes)) == 1) {
            r4ss <- TRUE
          }
          if(length(grep("change log", needs_changes)) == 1) {
            change_log <- TRUE
          }
          if(length(grep("SSI", needs_changes)) == 1) {
            SSI <- TRUE
          }
          if(length(grep("manual", needs_changes)) == 1) {
            manual <- TRUE
          }
          # Save the output to use in another step

        shell: Rscript {0}
        