name: Use the gh R pkg to get info from a PR
on:
  pull_request:

jobs:
  get-info-pr-gh-r-pkg:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: install the gh pkg
        run: install.packages("gh")
        shell: Rscript {0}
      - name: Get pr info and save
        run: |
          Rscript -e 'info <- gh::gh("GET /repos/{owner}/{repo}/pulls/{pull_number}", 
            owner = "k-doering-noaa", 
            repo = "test_github_site",
            pull_number = "${{ github.event.pull_request.number }}")
          saveRDS(info, file = "info.RDS")'
      - name: Post issues, if needed
        run: |
          info <- readRDS("info.RDS")
          pr_body  <- strsplit(info$body, "\n" )[[1]]
          pr_body <- gsub("\r", "",  pr_body, fixed = TRUE)
          # Get info on which repos need open issues, if a change log entry is needed.
          # allow some flexibility for getting the spacing wrong, which is easy to do.
          # look for checklist items like - []
          needs_changes <- grep("-\\s*\\[\\s*\\]", pr_body, ignore.case = TRUE, value = TRUE)
          issue_title <- paste0("Changes need for SS3 PR ",  info$number)
          issue_body <- paste0("Changes are needed due to the merging of SS3 \n", 
            "PR #", info$number, ". Please see \n", 
            "https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/", 
            info$number, "\nand its associated issues for more information.")
          if (length(grep("r4ss", needs_changes)) == 1) {
            gh::gh("POST /repos/{owner}/{repo}/issues",
             owner = "k-doering-noaa", 
             repo = "learn_tmb", 
             title = issue_title,
             body = issue_body)
          }
        shell: Rscript {0}