name: Get info from the body of a pull request
on: push
jobs:
  get-info-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          github-token: ${{ secrets.GH_PAT }}
          result-encoding: string
          script: |
            const result = github.rest.pulls.get({ 
              owner: context.repo.owner,
              repo: context.repo.repo, 
              pull_number: 22 });
            return result
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
        
